version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  myjob:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - print_pipeline_id

workflows:
  my_workflow:
    jobs:
      - myjob

